version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.3.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
        name: Bundle install
        command: bundle install
        working_directory: ios
      - run:
        name: Fastlane
        command: bundle exec fastlane test
        working_directory: ios
      - store_artifacts:
        path: output
      - store_test_results:
        path: output/scan

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
