version: 2
jobs:
  test-golang:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go build ./...
      - run: go test ./...

  test-ios:
    macos:
      xcode: "11.3.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
        name: Bundle install
        command: bundle install
        working_directory: ios
      - run:
        name: Fastlane
        command: bundle exec fastlane test
        working_directory: ios
      - store_artifacts:
        path: output
      - store_test_results:
        path: output/scan

workflows:
  version: 2
  all:
    jobs:
      - test-ios
      - test-golang
